version: "3.5"

services:
- name: plantasia-space-site
  github:
    branch: main
    deploy_on_push: true
    repo: plantasia-space/plantasia.space-site
  dockerfile_path: docker/Dockerfile
  source_dir: /
  http_port: 4000
  routes:
    - path: /
  environment_slug: ruby
  envs:
    - key: JEKYLL_ENV
      scope: RUN_AND_BUILD_TIME
      value: production