version: "3.5"

services:
  plantasia-space_build:
    image: docker_plantasia-space_dev
    environment:
      - JEKYLL_ENV
    ports:
      - 4000:4000
    container_name: plantasia-space_build
    volumes:
      - ..:/usr/src/app
    command: bundle exec jekyll build
  plantasia-space_web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    container_name: plantasia-space_web
    restart: unless-stopped
    volumes:
      - ../_site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - plantasia-space_build
