version: "3.5"

services:
  plantasia-space-site:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: plantasia-space-site_dev
    container_name: plantasia-space-site_dev
    environment:
      - JEKYLL_ENV=development
    ports:
      - "4000:4000"
    volumes:
      - ..:/usr/src/app  # Mount entire repo correctly
      - /usr/src/app/_site  # Prevents conflicts with _site
    command: bundle exec jekyll serve --host 0.0.0.0 --watch --drafts