version: "3.5"

services:
  plantasia-space-dev:
    image: registry.digitalocean.com/your-registry-name/plantasia-space-dev
    environment:
      - JEKYLL_ENV=development
    ports:
      - "4000:4000"
    container_name: plantasia-space-dev
    volumes:
      - .:/usr/src/app  # Corrected path
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve --host 0.0.0.0 --watch --config ./docs/_config.dev.yml