version: "3.5"

services:
  plantasia-space_build:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: plantasia-space-prod
    container_name: plantasia-space_build
    environment:
      - JEKYLL_ENV=production
    volumes:
      - ./_site:/usr/share/nginx/html
    command: bundle exec jekyll build

  plantasia-space_web:
    image: nginx
    container_name: plantasia-space_web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443"
    volumes:
      - ./_site:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - plantasia-space_build